name = "CGAL_jll"
uuid = "8fcd9439-76b0-55f4-a525-bad0597c05d8"
version = "5.0.1+0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
GMP_jll = "781609d7-10c4-51f6-84f2-b8444358ff6d"
MPFR_jll = "3a97d323-0669-5f0c-9066-3539efd106a3"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
boost_jll = "28df3c45-c428-5900-9ff8-a3135698ca75"

[compat]
julia = "1.0"
